export { renderIconSymbol } from './renderIconSymbol';
export {
  PlaceholderAdd,
  PlaceholderCheck,
  PlaceholderChevronDown,
  PlaceholderChevronLeft,
  PlaceholderChevronRight,
  PlaceholderChevronsLeft,
  PlaceholderChevronsRight,
  PlaceholderChevronsUpDown,
  PlaceholderChevronUp,
  PlaceholderClose,
  PlaceholderError,
  PlaceholderEye,
  PlaceholderEyeOff,
  PlaceholderInfo,
  PlaceholderLock,
  PlaceholderRemove,
  PlaceholderSuccess,
  PlaceholderWarning,
} from './placeholderIcons';
